export const START_POLLING_LATEST = 'START_POLLING_LATEST';
export const CANCEL_POLLING_LATEST = 'CANCEL_POLLING_LATEST';
export const POLLING_ERROR = 'POLLING_ERROR';
export const POLL_LATEST = 'POLL_LATEST';
export const RECEIVE_LATEST = 'RECEIVE_LATEST';

export const UPDATE_EXCHANGE_AMOUNT = 'UPDATE_EXCHANGE_AMOUNT';
export const UPDATE_EXCHANGE_FROM = 'UPDATE_EXCHANGE_FROM';
export const UPDATE_EXCHANGE_TO = 'UPDATE_EXCHANGE_TO';

export const EXCHANGE_CURRENT_USER = 'EXCHANGE_CURRENT_USER';
