export const START_POLLING_LATEST = 'START_POLLING_LATEST';
export const CANCEL_POLLING_LATEST = 'CANCEL_POLLING_LATEST';
export const POLLING_ERROR = 'POLLING_ERROR';
export const POLL_LATEST = 'POLL_LATEST';
export const RECEIVE_LATEST = 'RECEIVE_LATEST';
